team_map = \
    {
     '49ers':'SF',
     'Cardinals': 'AZ',
     'Falcons': 'ATL',
     'Ravens':'BAL',
     'Bills':'BUF',
     'Panthers':'CAR',
     'Bears':'CHI',
     'Bengals':'CIN',
     'Browns':'CLE',
     'Cowboys':'DAL',
     'Broncos':'DEN',
     'Lions':'DET',
     'Packers':'GB',
     'Texans':'HOU',
     'Colts':'IND',
     'Jaguars':'JAX',
     'Chiefs':'KC',
     'Rams':'LA',
     'Chargers':'LAC',
     'Dolphins':'MIA',
     'Vikings':'MIN',
     'Patriots':'NE',
     'Saints':'NO',
     'Giants':'NYG',
     'Jets':'NYJ',
     'Raiders':'OAK',
     'Eagles':'PHI',
     'Steelers':'PIT',
     'Seahawks':'SEA',
     'Buccaneers':'TB',
     'Titans':'TEN',
     'Redskins':'WAS'
    }